# Generated by Django 5.1.7 on 2025-05-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydetails',
            old_name='recipient_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
