# Generated by Django 5.1.7 on 2025-05-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='pincode',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
