# Generated by Django 5.1.7 on 2025-05-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_deliverydetails_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersummary',
            name='book_object',
        ),
        migrations.AddField(
            model_name='ordersummary',
            name='book_object',
            field=models.ManyToManyField(to='ecommerceapp.book'),
        ),
    ]
