# Generated by Django 5.1.7 on 2025-05-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_ordersummary_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
