# Generated by Django 5.1.7 on 2025-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_deliverydetails_user_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
