# Generated by Django 5.1.7 on 2025-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_alter_ordersummary_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
