# Generated by Django 5.1.7 on 2025-06-10 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_obj', models.ManyToManyField(to='ecommerceapp.book')),
                ('user_obj', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
