# Generated by Django 5.1.7 on 2025-06-10 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_favourites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='book_obj',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='user_obj',
        ),
        migrations.AddField(
            model_name='favourites',
            name='book_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.book'),
        ),
        migrations.AddField(
            model_name='favourites',
            name='user_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
