# Generated by Django 5.1.7 on 2025-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0016_book_favourite_delete_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/blankprofile.jpeg', upload_to='profile_pics/'),
        ),
    ]
