# Generated by Django 5.1.7 on 2025-06-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0020_alter_deliverydetails_delivery_options_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='session_id',
        ),
    ]
